/**--------------------------------------------------------------------------------------------------------------------------------------

                                 CHECKPOINT 3

--------------------------------------------------------------------------------------------------------------------------------------**/
/**TODO 1: Write a stored procedure named ‘revenue_report’ which generates a revenue report for your boss, 
    that showcases the revenue generated by vehicles till now based on their city. 
    The report should be ordered in descending order of the revenue and would look something like this
    ‘{CITY_NAME} : {REVENUE}’ .In the end line of report, also print: ‘Total Revenue: {TOTAL_REVENUE}’. 
    The report should include all the cities available in the database and if they haven't generated any revenue, show  the revenue as 0.
**/
SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE revenue_report
IS
    c_city_name city.city_name%TYPE;
    c_revenue booking.amount%TYPE;
    c_total_revenue number;
    CURSOR c_report is
        SELECT C.city_name,SUM(B.amount) AS Revenue FROM booking B RIGHT JOIN location L ON L.location_id=B.location_id 
        RIGHT JOIN city C ON L.city_id=C.city_id  GROUP BY C.city_name ORDER BY Revenue DESC NULLS LAST; 
BEGIN
    c_total_revenue:=0;
    OPEN c_report; 
    dbms_output.put_line('---Revenue Report---');
    dbms_output.put_line('City : Revenue');
    LOOP 
    FETCH c_report INTO c_city_name, c_revenue; 
        EXIT WHEN c_report%NOTFOUND; 
        IF c_revenue is null THEN
            dbms_output.put_line(c_city_name || ' : 0');
        ELSE
            dbms_output.put_line(c_city_name || ' : ' || c_revenue);
            c_total_revenue:=c_total_revenue+c_revenue;
        END IF;
    END LOOP;
        dbms_output.put_line('Total Revenue: ' || c_total_revenue);
    CLOSE c_report;
END;
/

EXECUTE revenue_report;




