/**TODO  2: Find the revenue generated by every vehicle and display them in descending order of their revenue amount. Only list those vehicles which have had any bookings. The returned table should contain 2 columns:
1. Vehicle_id
2. Amount generated by that particular vehicle as Revenue **/
SELECT B.vehicle_id, SUM(B.amount) AS Revenue FROM booking B 
GROUP BY B.vehicle_id 
ORDER BY Revenue DESC;
